### ISSUE TITLE
Add this as a community plugin

### ISSUE THREAD

**Issue by husseljoo** [martenlienen/obsidian-periodic-notes-navbar#1]
It would be cool if you could add this to the obsidian community plugins.
copying a directory into the vault can be a little mundane.

**Comment by martenlienen** [comment]
Hey, I don't see how this could be made into a community plugin, because it is not an extension itself but basically a collection of templates for Templater which need to go into your templates folder (and potentially be further customized by you). But if you see a way, I would like to hear about it!
